# Generated by Django 3.1 on 2020-09-11 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('othername', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('school', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=150)),
                ('cclass', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('ambition', models.CharField(max_length=50)),
                ('bornagain', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=150)),
            ],
        ),
    ]
